### ISSUE TITLE
Error: Twig Templates in sub-folders

### ISSUE THREAD

**Issue by mj1985** [heimrichhannot/contao-twig-support-bundle#11]
**Context**
Contao version: 4.13.35
Bundle version:  1.6.1 & 1.6.2
PHP version: 8.1

**Description**
Since version 1.6.1 twig templates in sub-folders won't be recognized. 
Settings in `config.yml`:
```
huh_twig_support:
    enable_template_loader: true
```
disabling the template-loader makes no differentes. 

Error:
`Uncaught PHP Exception Twig\Error\LoaderError: "Template "@Contao/mod_navbar-toggler.html.twig" is not defined."`

Our folder structure:
`/templates/modules/mod_navbar-toggler.html.twig`
`/templates/custom-elements/rsce_teaser.html.twig`

Moving the `mod_navbar-toggler.html.twig` or `rsce_teaser.html.twig` file to `/templates/` resolves the error, but we would like to keep the sub-folders structure.

**Comment by koertho** [comment]
Hi, thanks for reporting, I will have a look into it. 
But why don't you store the templates within /contao/templates? This is also the contao-supported way.

**Comment by koertho** [comment]
(and you won't need the templates loader in 4.13 anymore)
