### ISSUE TITLE
Fehler nach Update 

### ISSUE THREAD

**Issue by Olli** [heimrichhannot/contao-twig-support-bundle#2]
Hi 
ich habe heute mal wieder geupdatet und bekam folgende Meldung schon beim Contao installer

```
request.CRITICAL: Uncaught PHP Exception TypeError: "Return value of HeimrichHannot\TwigSupportBundle\Filesystem\TwigTemplateLocator::getTemplates() must be of the type array, null returned" at /mnt/*/vendor/heimrichhannot/contao-twig-support-bundle/src/Filesystem/TwigTemplateLocator.php line 258 {"exception":"[object] (TypeError(code: 0): Return value of HeimrichHannot\\TwigSupportBundle\\Filesystem\\TwigTemplateLocator::getTemplates() must be of the type array, null returned at /mnt/*/vendor/heimrichhannot/contao-twig-support-bundle/src/Filesystem/TwigTemplateLocator.php:258)"}
```

Contao 4.9.9  Utils Bundle 2.185.0, List Bundle 1.30.1

**Comment by koertho** [comment]
Ich konnte den Fehler leider nicht reproduzieren. Ich habe mal in Version 0.2.7 bei zwei Funktionen die Rückgabe-Typ-Deklarationen hinzugefügt, eventuell bekommen wir dann einen genaueren Fehler. Kommt der Fehler beim Cache-Warmup?

**Comment by Olli** [comment]
Der Fehler kommt beim Seitenaufruf / Login

**Comment by koertho** [comment]
Jeder Seitenaufruf? Login Frontend oder Backend? Sei bitte bei deinen Fehlerbeschreibungen etwas ausführlicher.

**Comment by Olli** [comment]
Das kommt bei jedem Seitenaufruf und bei jedem Login. Contao ist in dem Moment einfach komplett unbenutzbar. Ich musste ein Backup einspielen.

**Comment by koertho** [comment]
Kannst du den Stack trace im dev modus bitte angeben?

**Comment by Olli** [comment]
Ich kann den Dev Modus nicht anschalten. Es gibt da irgend eine wilde Meldung im Contao Manager. Das ist ein Hosting bei Strato.
Ich habe jetzt die Install noch mal geupdated. Es tritt wieder auf. Ich habe 2 identische Installationen geupdated (all-Inkl und lokal). Da ist der Fehler nicht aufgetreten. 
Ein Downgrade auf 0.2.5 vom Twig Bundle brachte die Install wieder zum laufen.

**Comment by koertho** [comment]
Du kannst den Dev-Modus auch in Contao direkt einschalten. Im Backend in der Leiste oben. Oder über die .env-Datei im Projekt-Root (dort musst du `APP_ENV=dev` eintragen, hinterher aber das entfernen oder auskommentieren nicht vergessen). Du könntest aber auch den Log-Eintrag posten, eventuell ist der auch aussagekräftig genug.

**Comment by Olli** [comment]
Der Logeintrag ist im ersten Post enthalten. Danke für den Hinweis mit dem Dev Modus. Das wusste ich nicht und werde das heute Nachmittag mal probieren.

**Comment by koertho** [comment]
Es gab aber ja in der Zwischenzeit ein Update...da sollt der Fehler etwas präziser sein.

**Comment by Olli** [comment]
Ich bekomme jetzt folgende Meldung im Log
```
request.CRITICAL: Uncaught PHP Exception TypeError: "Return value of HeimrichHannot\TwigSupportBundle\Filesystem\TwigTemplateLocator::getTemplates() must be of the type array, null returned" at /mnt/*/vendor/heimrichhannot/contao-twig-support-bundle/src/Filesystem/TwigTemplateLocator.php line 258 {"exception":"[object] (TypeError(code: 0): Return value of HeimrichHannot\\TwigSupportBundle\\Filesystem\\TwigTemplateLocator::getTemplates() must be of the type array, null returned at /mnt*/vendor/heimrichhannot/contao-twig-support-bundle/src/Filesystem/TwigTemplateLocator.php:258)"} []

```

**Comment by koertho** [comment]
@Olli Ich habe gerade noch eine weitere Änderung eingespielt, welche den Fehler eventuell Lösen könnte. Testest du es bitte mit Version 0.2.8?

**Comment by Olli** [comment]
Super. Ich habe jetzt auf 0.2.8 geupdatet und die Contao Install läuft. Das hat es also gebracht. Vielen Dank.

**Comment by koertho** [comment]
@Olli Danke für die Rückmeldung!
